CREATE DATABASE IF NOT EXISTS phi_appointments;
CREATE DATABASE IF NOT EXISTS phi_audit;
CREATE DATABASE IF NOT EXISTS phi_ehr;
CREATE DATABASE IF NOT EXISTS phi_billing;
CREATE DATABASE IF NOT EXISTS phi_notification;
CREATE DATABASE IF NOT EXISTS phi_patient;
CREATE DATABASE IF NOT EXISTS phi_rbac;
CREATE DATABASE IF NOT EXISTS phi_reporting;
