"""Initial reporting schema

Revision ID: 61b4454b8a83
Revises:
Create Date: 2025-11-25 11:53:13.298286

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "61b4454b8a83"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reporting_appointments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("provider_id", sa.String(length=36), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("date_only", sa.Date(), nullable=False),
        sa.Column("appointment_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reporting_appointments_date_only"),
        "reporting_appointments",
        ["date_only"],
        unique=False,
    )
    op.create_table(
        "reporting_patients",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("registration_date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reporting_patients_registration_date"),
        "reporting_patients",
        ["registration_date"],
        unique=False,
    )
    op.create_table(
        "reporting_transactions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("patient_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("transaction_date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reporting_transactions_transaction_date"),
        "reporting_transactions",
        ["transaction_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_reporting_transactions_transaction_date"),
        table_name="reporting_transactions",
    )
    op.drop_table("reporting_transactions")
    op.drop_index(
        op.f("ix_reporting_patients_registration_date"), table_name="reporting_patients"
    )
    op.drop_table("reporting_patients")
    op.drop_index(
        op.f("ix_reporting_appointments_date_only"), table_name="reporting_appointments"
    )
    op.drop_table("reporting_appointments")
    # ### end Alembic commands ###
