"""Initial postgres migration

Revision ID: 9744aaaedfc4
Revises: 
Create Date: 2025-12-06 10:28:18.152951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9744aaaedfc4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('related_resource_type', sa.String(length=50), nullable=True),
    sa.Column('related_resource_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_history')
    # ### end Alembic commands ###
